<html>
    <head>

    </head>
    <body>
        <tr>
            <td class="header">
            <a href="#" style="display: inline-block;">
            <img src="https://lnmu.ac.in/Frontend/images/icon/newlnmu.gif" class="logo" alt="LNMU Logo" style="height:50px;width:50px;">
            </a>
            </td>
            <td>
                <h1>Register Your Self as Faculty Of LNMU</h1>
            </td>
            </tr>
        
        <div>
            <br><br><br><br>
            This email is generated by IT-Cell LNMU . Please Register Your self - <br/>Link is given below -<br/> <br><br>
            <a href="{{$userlink}}" style=" background-color: #008CBA;;border: none;color: white;padding: 15px 32px;text-align: center;
            text-decoration: none;display: inline-block;font-size: 16px;"><b> Register Your Self</b></a>
        </div>
    </body>
</html>


